networks:
  internal-net:
    external: true
    driver: bridge

volumes:
  log_volume:
    
services:
  dragoon-logger:
    restart: unless-stopped
    container_name: dragoon-logger
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - log_volume:/var/lib/log_volume/data/
    env_file:
      - .env
    expose:
      - 15000
    networks:
      - internal-net