apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: dragoon-log-hpa
  namespace: ${NAMESPACE}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dragoon-logger
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        averageValue: 80m
        type: AverageValue
