name: CD DRAGON-staging

on:
  push:
    branches:
      - 'dev'
  workflow_dispatch:

env:
  SECRETS: ${{ secrets.SECRET_ENV }}

jobs:
  Deploy_Dragoon_Log_Worker:
    name: deploy dragoon-log worker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .ENV
        run: |
          python .github/copy_dotenv.py

      - name: Upload application
        uses: appleboy/scp-action@master
        with:       
          host: ${{ secrets.SERVER_IP_ADDRESS }}        
          username: ${{ secrets.SERVER_USERNAME }}      
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          source: "."      
          target: "~/dragon-worker/"

      - name: Deploy Dragoon
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}       
          username: ${{ secrets.SERVER_USERNAME }}     
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            cd $HOME/dragon-worker/ 
            sudo docker network create internal-net
            ll
            sudo docker-compose -f docker-compose.yaml up --build -d
            cd ..

      - name: Delete Files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP_ADDRESS }}       
          username: ${{ secrets.SERVER_USERNAME }}     
          key: ${{ secrets.SERVER_KEY }}
          port: 22
          script: |
            sudo rm -r $HOME/dragon-worker/

  Deploy_Dragoon_Log_UI:
    name: deploy dragoon-log UI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create .ENV
        run: |
          python .github/copy_dotenv.py

      # - name: Upload application
      #   uses: appleboy/scp-action@master
      #   with:       
      #     host: ${{ secrets.SERVER_IP_ADDRESS }}        
      #     username: ${{ secrets.SERVER_USERNAME }}      
      #     key: ${{ secrets.SERVER_KEY }}
      #     port: 22
      #     source: "."      
      #     target: "~/dragon-ui/"

      # - name: Deploy Service
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_IP_ADDRESS }}       
      #     username: ${{ secrets.SERVER_USERNAME }}     
      #     key: ${{ secrets.SERVER_KEY }}
      #     port: 22
      #     script: |
      #       cd $HOME/dragon-ui/ 
      #        sudo docker network create internal-net
      #       sudo docker-compose -f .Ultimate-Log/docker-compose.yml up --build -d
      #       cd ..

      # - name: Delete Files
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.SERVER_IP_ADDRESS }}       
      #     username: ${{ secrets.SERVER_USERNAME }}     
      #     key: ${{ secrets.SERVER_KEY }}
      #     port: 22
      #     script: |
      #       sudo rm -r $HOME/dragon-ui/
